### ISSUE TITLE
补🦌功能报错

### ISSUE THREAD

**Issue by ElainaFanBoy** [SamuNatsu/nonebot-plugin-deer-pipe#14]
```
2024-12-03 19:16:40,800 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-12-03 19:16:40,801 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("user")
2024-12-03 19:16:40,801 INFO sqlalchemy.engine.Engine [raw sql] ()
12-03 19:16:40 [SUCCESS] nonebot | OneBot V11 3664798329 | [notice.notify.poke]: {'time': 1733224600, 'self_id': 3664798329, 'post_type': 'notice', 'notice_type': 'notify', 'sub_type': 'poke', 'user_id': 3586987213, 'group_id': 192912923, 'target_id': 3889016014, 'raw_info': [{'col': '1', 'nm': '', 'type': 'qq', 'uid': 'u_sduFESAkV2Cn4hFUBZxg-g'}, {'jp': 'https://zb.vip.qq.com/v2/pages/nudgeMall?_wv=2', 'src': 'http://tianquan.gtimg.cn/nudgeaction/item/0/expression.jpg', 'type': 'img'}, {'txt': '戳了戳', 'type': 'nor'}, {'col': '1', 'nm': '', 'tp': '0', 'type': 'qq', 'uid': 'u_tLZfLm89F2ukIpjfA3EdcA'}, {'txt': '', 'type': 'nor'}]}
12-03 19:16:40 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=nonebot_plugin_auto_bot_selector.target, lineno=17)
12-03 19:16:41 [SUCCESS] nonebot | OneBot V11 3664798329 | [message.group.normal]: Message 1630914890 from 1041433615@[群:722713727] '能省就省'
2024-12-03 19:16:41,193 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("userdeer")
2024-12-03 19:16:41,193 INFO sqlalchemy.engine.Engine [raw sql] ()
12-03 19:16:41 [INFO] nonebot | Matcher(type='notice', module=nonebot_plugin_auto_bot_selector.target, lineno=17) running complete
2024-12-03 19:16:41,297 INFO sqlalchemy.engine.Engine COMMIT
12-03 19:16:41 [INFO] nonebot | Event will be handled by Matcher(type='', module=src.test.nonebot_plugin_essence_message, lineno=32)
12-03 19:16:41 [INFO] nonebot | Matcher(type='', module=src.test.nonebot_plugin_essence_message, lineno=32) running complete
12-03 19:16:41 [INFO] nonebot | Event will be handled by Matcher(type='', module=src.test.nonebot_plugin_essence_message, lineno=62)
12-03 19:16:41 [INFO] nonebot | Matcher(type='', module=src.test.nonebot_plugin_essence_message, lineno=62) running complete
2024-12-03 19:16:41,605 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-12-03 19:16:41,608 INFO sqlalchemy.engine.Engine SELECT user.id, user.group_id, user.avatar_data
FROM user
WHERE user.id = ?
2024-12-03 19:16:41,608 INFO sqlalchemy.engine.Engine [generated in 0.00067s] ('712111161',)
2024-12-03 19:16:41,679 INFO sqlalchemy.engine.Engine ROLLBACK
2024-12-03 19:16:42,204 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-12-03 19:16:42,204 INFO sqlalchemy.engine.Engine SELECT user.id, user.group_id, user.avatar_data
FROM user
WHERE user.id = ?
2024-12-03 19:16:42,205 INFO sqlalchemy.engine.Engine [cached since 0.5973s ago] ('712111161',)
2024-12-03 19:16:42,227 INFO sqlalchemy.engine.Engine ROLLBACK
12-03 19:16:42 [INFO] nonebot | AlconnaMatcher(type='', module=src.test.nonebot_plugin_deer_pipe, lineno=40) running complete
12-03 19:16:42 [ERROR] nonebot | Running AlconnaMatcher(type='', module=src.test.nonebot_plugin_deer_pipe, lineno=40) failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\lastload\nonebot_plugin_reboot\reloader.py", line 27, in _run
    _nb_run(*args, **kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\uvicorn\server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\test\nonebot_plugin_deer_pipe\__init__.py", line 85, in handle_deer_reattend
    await add_user_avatar(user_info.user_id, user_avatar)
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\src\test\nonebot_plugin_deer_pipe\database.py", line 97, in add_user_avatar
    user.avatar = avatar
  File "D:\Desktop\0\software\wbushu\Bot\IRONY\env\lib\site-packages\sqlmodel\main.py", line 824, in __setattr__
    super().__setattr__(name, value)
  File "pydantic\main.py", line 357, in pydantic.main.BaseModel.__setattr__
    raise ValueError(f'"{self.__class__.__name__}" object has no field "{name}"')
ValueError: "User" object has no field "avatar"
```

**Comment by SamuNatsu** [comment]
git 最新版本无法保障稳定，请回退到上一 release 版本，我正在重写改插件
